import type { Profile } from "@/types/independent";

export const DEMO_CREATORS: Profile[] = [
  {
    id: "creator-01",
    display_name: "Sofía Reyes",
    username: "sofia_tech",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80",
    bio: "AI Founder & Software Engineer. Construyo agentes y herramientas para creadores. Busco co-crear contenido de tecnología y lanzar apps conjuntas.",
    city: "Madrid",
    country: "España",
    discipline: "tech_founder",
    genres: ["Tech & IA", "Startups", "Educación"],
    skills: ["Desarrollo Frontend", "IA generativa", "Growth hacking"],
    experience_level: "pro",
    years_active: 5,
    looking_for: ["influencer", "videographer", "brand_sponsor"],
    instagram_url: "https://instagram.com/sofia.tech",
    tiktok_url: "https://tiktok.com/@sofia_dev",
    youtube_url: "https://youtube.com/@sofiareyesdev",
    x_url: "https://x.com/sofia_ai",
    linkedin_url: "https://linkedin.com/in/sofia-reyes-tech",
    spotify_url: null,
    soundcloud_url: null,
    twitch_url: null,
    website_url: "https://sofia.tech",
    social_stats: {
      instagram_followers: "84.2K seg.",
      tiktok_followers: "165K seg.",
      youtube_subs: "42.5K subs",
      total_reach: "+290K Alcance",
      engagement_rate: "5.4%",
      primary_platform: "TikTok",
    },
    collab_offerings: ["Desarrollo Web / App / IA", "Audiencia Tech & Devs", "Storytelling de Producto"],
    collab_seeking: ["Creadores de Contenido para Campañas", "Lanzar Producto Compartido", "Podcast Invitado"],
    brand_pitch: "Audiencia fiel de programadores y early adopters. Capacidad para viralizar lanzamientos de software.",
    synergy_tagline: "Listo para co-crear herramientas que automaticen el trabajo de creadores y marcas.",
    is_verified: true,
    verified_at: "2026-01-10T12:00:00Z",
    onboarding_completed: true,
    created_at: "2026-01-01T10:00:00Z",
    updated_at: "2026-03-01T10:00:00Z",
    notification_prefs: null,
  },
  {
    id: "creator-02",
    display_name: "Mateo Silva",
    username: "teosilva_fit",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80",
    bio: "Atleta Hyrox & Coach de Rendimiento. Ayudo a optimizar salud física y mental sin complicaciones.",
    city: "Buenos Aires",
    country: "Argentina",
    discipline: "fitness_coach",
    genres: ["Fitness & Calistenia", "Lifestyle", "Desarrollo Personal"],
    skills: ["TikTok / Reels virales", "Comunidad activa", "Campañas con marcas"],
    experience_level: "pro",
    years_active: 6,
    looking_for: ["brand_sponsor", "videographer", "influencer"],
    instagram_url: "https://instagram.com/teosilva_fit",
    tiktok_url: "https://tiktok.com/@mateosilva.fit",
    youtube_url: "https://youtube.com/@mateosilva",
    x_url: null,
    linkedin_url: null,
    spotify_url: null,
    soundcloud_url: null,
    twitch_url: null,
    website_url: "https://teosilva.com",
    social_stats: {
      instagram_followers: "215K seg.",
      tiktok_followers: "480K seg.",
      youtube_subs: "68K subs",
      total_reach: "+760K Alcance",
      engagement_rate: "7.1%",
      primary_platform: "TikTok",
    },
    collab_offerings: ["Audiencia Fitness & Bienestar", "Producción de Reels en Gimnasio", "Rostro y Motivación"],
    collab_seeking: ["Marcas de Ropa Deportiva / Suplementos", "Cross-Promo con Nutricionistas", "Videógrafo Pro"],
    brand_pitch: "Contenido 100% verificado con alta conversión en productos de rendimiento y estilo de vida activo.",
    synergy_tagline: "Explotemos campañas de salud y retos virales para marcas con propósito.",
    is_verified: true,
    verified_at: "2026-02-15T12:00:00Z",
    onboarding_completed: true,
    created_at: "2026-01-05T10:00:00Z",
    updated_at: "2026-03-05T10:00:00Z",
    notification_prefs: null,
  },
  {
    id: "creator-03",
    display_name: "Valentina Gómez",
    username: "valengomez",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&auto=format&fit=crop&q=80",
    bio: "Fashion, Streetwear & Dirección Creativa. Curadora de estilo, outfits en movimiento y estética vanguardista.",
    city: "Ciudad de México",
    country: "México",
    discipline: "stylist",
    genres: ["Moda & Streetwear", "Lifestyle", "Diseño & 3D"],
    skills: ["Fotografía editorial", "Estilismo y vestuario", "Storytelling"],
    experience_level: "pro",
    years_active: 4,
    looking_for: ["brand_sponsor", "photographer", "designer"],
    instagram_url: "https://instagram.com/valengomez_style",
    tiktok_url: "https://tiktok.com/@valen_outfits",
    youtube_url: null,
    x_url: "https://x.com/valengomez",
    linkedin_url: null,
    spotify_url: null,
    soundcloud_url: null,
    twitch_url: null,
    website_url: null,
    social_stats: {
      instagram_followers: "340K seg.",
      tiktok_followers: "690K seg.",
      total_reach: "+1.03M Alcance",
      engagement_rate: "6.8%",
      primary_platform: "Instagram",
    },
    collab_offerings: ["Comunidad Gen-Z & Millennial", "Dirección Visual Editorial", "Integraciones Orgánicas de Marca"],
    collab_seeking: ["Marcas de Moda / Accesorios", "Fotógrafos Editoriales", "Línea de Ropa Co-branded"],
    brand_pitch: "Impacto visual garantizado y engagement superior al promedio en el nicho de moda y estética.",
    synergy_tagline: "Diseñemos colecciones cápsula o campañas de moda que destaquen visualmente en el feed.",
    is_verified: true,
    verified_at: "2026-01-20T12:00:00Z",
    onboarding_completed: true,
    created_at: "2026-01-08T10:00:00Z",
    updated_at: "2026-03-08T10:00:00Z",
    notification_prefs: null,
  },
  {
    id: "creator-04",
    display_name: "Lucas Chen",
    username: "chenvisuals",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80",
    bio: "3D Artist & Motion Designer. Creo universos visuales para marcas globales, videoclips y campañas CGI hiperrealistas.",
    city: "Barcelona",
    country: "España",
    discipline: "designer",
    genres: ["Diseño & 3D", "Tech & IA", "Cine & Series"],
    skills: ["Dirección de arte", "IA generativa", "Edición Premiere / CapCut"],
    experience_level: "pro",
    years_active: 7,
    looking_for: ["brand_sponsor", "producer", "tech_founder"],
    instagram_url: "https://instagram.com/chenvisuals",
    tiktok_url: "https://tiktok.com/@chen_3d",
    youtube_url: "https://youtube.com/@chenmotion",
    x_url: "https://x.com/chen_cgi",
    linkedin_url: null,
    spotify_url: null,
    soundcloud_url: null,
    twitch_url: null,
    website_url: "https://chenvisuals.com",
    social_stats: {
      instagram_followers: "128K seg.",
      tiktok_followers: "95K seg.",
      youtube_subs: "38K subs",
      total_reach: "+260K Alcance",
      engagement_rate: "8.2%",
      primary_platform: "Instagram",
    },
    collab_offerings: ["Animación 3D y CGI de Cine", "Branding de Alto Impacto", "Efectos Visuales para Video"],
    collab_seeking: ["Artistas Musicales para Videoclips", "Startups Tech que busquen 3D", "Campañas de Marca"],
    brand_pitch: "Transformo productos en piezas de arte visual 3D que generan retención máxima en redes.",
    synergy_tagline: "Listo para llevar la imagen de cualquier creador o marca al nivel visual de un estudio de Hollywood.",
    is_verified: true,
    verified_at: "2026-01-25T12:00:00Z",
    onboarding_completed: true,
    created_at: "2026-01-12T10:00:00Z",
    updated_at: "2026-03-12T10:00:00Z",
    notification_prefs: null,
  },
  {
    id: "creator-05",
    display_name: "Camila Torres",
    username: "camitorres",
    avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80",
    bio: "Streamer en Twitch & Creadora de Gaming / Tech setup. Comunidad súper unida de más de 400K fans en toda LATAM.",
    city: "Bogotá",
    country: "Colombia",
    discipline: "streamer",
    genres: ["Gaming & Esports", "Humor & Entretenimiento", "Tech & IA"],
    skills: ["Live streaming", "Comunidad activa", "Campañas con marcas"],
    experience_level: "pro",
    years_active: 4,
    looking_for: ["brand_sponsor", "podcaster", "influencer"],
    instagram_url: "https://instagram.com/camitorres.live",
    tiktok_url: "https://tiktok.com/@camitorres_clips",
    youtube_url: "https://youtube.com/@camitorresgames",
    twitch_url: "https://twitch.tv/camitorres",
    x_url: "https://x.com/camitorres_live",
    linkedin_url: null,
    spotify_url: null,
    soundcloud_url: null,
    website_url: null,
    social_stats: {
      instagram_followers: "190K seg.",
      tiktok_followers: "350K seg.",
      twitch_followers: "240K seg.",
      total_reach: "+780K Alcance",
      engagement_rate: "9.5%",
      primary_platform: "Twitch",
    },
    collab_offerings: ["Audiencia en Vivo (2.5K viewers promedio)", "Clips Virales para TikTok", "Activaciones de Marca en Stream"],
    collab_seeking: ["Sponsors de Hardware / Bebidas / Tech", "Co-streaming con otros Creadores", "Podcast de Invitada"],
    brand_pitch: "Conexión directa e interactiva en tiempo real con público gamer y entusiasta de tecnología.",
    synergy_tagline: "Colaboremos en directos dinámicos, dinámicas con marcas y eventos en vivo.",
    is_verified: true,
    verified_at: "2026-02-01T12:00:00Z",
    onboarding_completed: true,
    created_at: "2026-01-15T10:00:00Z",
    updated_at: "2026-03-15T10:00:00Z",
    notification_prefs: null,
  },
  {
    id: "creator-06",
    display_name: "Nico Morales",
    username: "nicocooks",
    avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80",
    bio: "Chef nómada & Creador Gastronómico. Recetas callejeras y de alta cocina contadas con ritmo y fotografía cinematográfica.",
    city: "Lima",
    country: "Perú",
    discipline: "culinary_creator",
    genres: ["Gastronomía", "Viajes & Aventura", "Lifestyle"],
    skills: ["TikTok / Reels virales", "Storytelling", "Edición Premiere / CapCut"],
    experience_level: "pro",
    years_active: 5,
    looking_for: ["brand_sponsor", "videographer", "influencer"],
    instagram_url: "https://instagram.com/nicocooks",
    tiktok_url: "https://tiktok.com/@nicocooks",
    youtube_url: "https://youtube.com/@nicomoraleschef",
    x_url: null,
    linkedin_url: null,
    spotify_url: null,
    soundcloud_url: null,
    twitch_url: null,
    website_url: null,
    social_stats: {
      instagram_followers: "280K seg.",
      tiktok_followers: "620K seg.",
      youtube_subs: "95K subs",
      total_reach: "+995K Alcance",
      engagement_rate: "8.0%",
      primary_platform: "TikTok",
    },
    collab_offerings: ["Videos de Recetas con Retención 80%+", "Integración de Productos Culinarios", "Eventos y Pop-ups Presenciales"],
    collab_seeking: ["Marcas de Alimentos / Restaurantes", "Colaboraciones con Creadores de Viajes", "Línea de Salsas Co-branded"],
    brand_pitch: "Contenido que despierta apetito y confianza inmediata. Audiencia familiar y joven apasionada por el buen comer.",
    synergy_tagline: "Cocinemos recetas virales y creemos experiencias gastronómicas memorables.",
    is_verified: true,
    verified_at: "2026-02-10T12:00:00Z",
    onboarding_completed: true,
    created_at: "2026-01-18T10:00:00Z",
    updated_at: "2026-03-18T10:00:00Z",
    notification_prefs: null,
  },
  {
    id: "creator-07",
    display_name: "Elena Navarro",
    username: "elena_growth",
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80",
    bio: "Head of Growth & Podcaster de Negocios. Ayudo a creadores a convertir seguidores en clientes y productos escalables.",
    city: "Santiago",
    country: "Chile",
    discipline: "marketing_agency",
    genres: ["Startups", "Educación Financiera", "Marketing Digital"],
    skills: ["Growth hacking", "SEO y copywriting", "Campañas con marcas"],
    experience_level: "pro",
    years_active: 8,
    looking_for: ["influencer", "tech_founder", "podcaster"],
    instagram_url: "https://instagram.com/elena_growth",
    tiktok_url: null,
    youtube_url: "https://youtube.com/@elenanavarrogrowth",
    x_url: "https://x.com/elena_growth",
    linkedin_url: "https://linkedin.com/in/elena-navarro-growth",
    spotify_url: null,
    soundcloud_url: null,
    twitch_url: null,
    website_url: "https://elenanavarro.io",
    social_stats: {
      instagram_followers: "62K seg.",
      youtube_subs: "28K subs",
      total_reach: "+175K Alcance",
      engagement_rate: "6.2%",
      primary_platform: "LinkedIn",
    },
    collab_offerings: ["Estrategias de Monetización & Funnels", "Lanzamientos de Cursos y Productos Digitales", "Conexión con Inversores y Marcas"],
    collab_seeking: ["Creadores con Audiencias Grandes para Co-crear Cursos", "Founders de Startups", "Invitados a Podcast"],
    brand_pitch: "Especialista en estructurar alianzas comerciales con reparto de ingresos (rev-share) rentable para ambas partes.",
    synergy_tagline: "Moneticemos tu comunidad con productos de alto valor y lanzamientos estratégicos.",
    is_verified: true,
    verified_at: "2026-01-30T12:00:00Z",
    onboarding_completed: true,
    created_at: "2026-01-20T10:00:00Z",
    updated_at: "2026-03-20T10:00:00Z",
    notification_prefs: null,
  },
  {
    id: "creator-08",
    display_name: "Nova Brand Co.",
    username: "novabrand",
    avatar_url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=500&auto=format&fit=crop&q=80",
    bio: "Marca de café de especialidad y estilo de vida activo. Buscamos embajadores de marca y co-creadores para campañas 2026.",
    city: "Medellín",
    country: "Colombia",
    discipline: "brand_sponsor",
    genres: ["Lifestyle", "Fitness & Calistenia", "Gastronomía"],
    skills: ["Co-branding", "Patrocinios y marcas", "Organización de eventos"],
    experience_level: "pro",
    years_active: 3,
    looking_for: ["influencer", "fitness_coach", "videographer"],
    instagram_url: "https://instagram.com/novacoffee.co",
    tiktok_url: "https://tiktok.com/@novabrand",
    youtube_url: null,
    x_url: null,
    linkedin_url: "https://linkedin.com/company/novacoffee",
    spotify_url: null,
    soundcloud_url: null,
    twitch_url: null,
    website_url: "https://novacoffee.co",
    social_stats: {
      instagram_followers: "98K seg.",
      tiktok_followers: "115K seg.",
      total_reach: "+213K Alcance",
      engagement_rate: "5.8%",
      primary_platform: "Instagram",
    },
    collab_offerings: ["Presupuesto de Patrocinio & Envíos de Producto", "Comisión por Venta (20% Rev-share)", "Co-branding en Empaques de Café"],
    collab_seeking: ["Creadores de Fitness, Lifestyle y Tech", "Contenido UGC Auténtico", "Embajadores de Marca a Largo Plazo"],
    brand_pitch: "Invertimos activamente en creadores con valores alineados al bienestar y la productividad.",
    synergy_tagline: "Buscamos rostros y creadores para patrocinar y co-crear la bebida de los creativos.",
    is_verified: true,
    verified_at: "2026-02-18T12:00:00Z",
    onboarding_completed: true,
    created_at: "2026-01-22T10:00:00Z",
    updated_at: "2026-03-22T10:00:00Z",
    notification_prefs: null,
  },
];
